TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.05
  max_vel_theta: 0.5 #1.0
  min_vel_theta: -0.5 #-1.0
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 1.6 #3.2
  acc_lim_x: 1.25 #2.5
  acc_lim_y: 0

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2

  holonomic_robot: false

  oscillation_reset_dist: 0.1
